### ISSUE TITLE
Add continuous integration in repository

### ISSUE THREAD

**Issue by willmendesneto** [albertogasparin/react-adone#1]
Add continuous integration with minimum of validations to run in pull requests/merge to master. So that we can make sure of some points, such as:

- Other folks can send a pull request with confidence;
- There's transparency on the tasks, with no requirement to pull the changes locally, having checks that give confidence for reviewers;

**Comment by albertogasparin** [comment]
Done! I also added a couple of badges, because it's cool 😜

**Comment by willmendesneto** [comment]
Good that you mentioned badges 🙃

https://github.com/albertogasparin/react-adone/issues/4
