### ISSUE TITLE
Add code coverage badge

### ISSUE THREAD

**Issue by willmendesneto** [albertogasparin/react-adone#4]
Add code coverage integration will make you able to:

- Bring transparency about code coverage percentage, adding it on `README.md`;
- Encourage new contributors since your code coverage is visible for everyone with no requirement to visit Circle CI or any other website;
- Understand what happened in case the coverage was decreased;

Possible approaches/toolings to use in the integration

- Coveralls.io: https://coveralls.io/;
- Codecov: https://codecov.io/

**Comment by albertogasparin** [comment]
Done.
