### ISSUE TITLE
Ensure updates to listeners fire top to bottom

### ISSUE THREAD

**Issue by albertogasparin** [albertogasparin/react-adone#7]
On nested yields looking at the same basket Adone should fire updates from top to bottom to reduce the numbers of re-renders.

```js
<Yield from={basket} pick={x}>
  {({ dataX }) => (
    <Yield from={basket} pick={y}>
      {({ dataY }) => (
        <Yield from={basket} pick={z}>
          {({ dataZ }) => (
            console.log('render')
          )}
        </Yield>
      )}
    </Yield>
  )}
</Yield>
```

Expect `console.log` to have been called once.

**Comment by ferborva** [comment]
🧐

**Comment by albertogasparin** [comment]
The order in which listeners are currently created is correct: [listenerX, listenerY, listenerZ]
So if the basket is updated, X trigger the render and Y, Z are updated during the parent render cycle without requiring another re-render.
The problem is when we have parallel trees: 

```js
<Yield from={counterBasket}>{({ count }) => <p>{count}</p>}</Yield>
<Yield from={counterBasket}>{({ count }) => <p>{count}</p>}</Yield>
```

If the update is triggered outside the user interaction event (eg. after `await`) then React won't batch the updates of the two trees, committing the changes twice. The difference in performance looks quite substantial, as I observed a **regression** of ~ 40% (React dev version, but still...)

![batched diff](https://user-images.githubusercontent.com/84136/47249312-e1caa000-d45d-11e8-83de-57c213368755.png)

One solution could be implementing a middleware that wraps our produce updates with  `ReactDOM.unstable_batchedUpdates` to force batched updates:

```js
import ReactDOM from 'react-dom';
import { defaults } from 'react-adone';

const batchedUpdatesMw = () => next => fn => {
  let result;
  ReactDOM.unstable_batchedUpdates(() => {
    result = next(fn);
  });
  return result;
};
defaults.middlewares.add(batchedUpdatesMw);
```

However, this should be considered a temporary solution as `unstable_batchedUpdates` API is probably going to be removed with React 17, where setState calls will always batched.

Adone could implement this middleware anyway in the meantime, but I see 2 problems: 
1. We will add ReactDOM dependency, preventing Adone from working in other React contexts (eg native)
2. We might introduce issues on SSR

So the best option could be document this solution and let consumers add the middleware themselves if they are particularly concerned about performance (until React 17 comes)
